README.md, docs/versions/v3.md
- Update README
- Add V3 document
=> Update README and Add v3 docs

README.md, lib/routes_to_swagger_docs/configuration.rb, lib/routes_to_swagger_docs/generator/base_generator.rb
- Replace from `schema_save_dir_path` to `schema_save_dir_name`
- Replace from `doc_save_file_path` to `doc_save_file_name`
=> Modify configure option

lib/routes_to_swagger_docs/routing/parser.rb, lib/routes_to_swagger_docs/schema/analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/components/schemas_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/components_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/path_analyzer.rb, lib/routes_to_swagger_docs/schema/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/generator/components/schema_generator.rb, lib/routes_to_swagger_docs/schema/generator/components_generator.rb, lib/routes_to_swagger_docs/schema/generator/path_generator.rb, lib/routes_to_swagger_docs/schema/generator/schema_generator.rb, lib/routes_to_swagger_docs/schema/squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/components/schema_squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/components_squeezer.rb, lib/routes_to_swagger_docs/schema/v3/components_object.rb, lib/routes_to_swagger_docs/schema/v3/openapi_object.rb, lib/routes_to_swagger_docs/schema/v3/path_item_object.rb, lib/routes_to_swagger_docs/schema/v3/schema_object.rb
To be able to support `$ref` in paths schema.
=> Support reference in paths schema

README.md, docs/HOW_TO_START_SWAGGER_UI.md, lib/routes_to_swagger_docs/schema/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/ui.rb, lib/routes_to_swagger_docs/schema/v3/server_object.rb, lib/routes_to_swagger_docs/tasks/swagger.rake
=> Support open swagger ui

lib/routes_to_swagger_docs/schema/analyzer/base_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/components/schemas_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/path_analyzer.rb, lib/routes_to_swagger_docs/schema/base.rb, lib/routes_to_swagger_docs/schema/generator/components/schema_generator.rb, lib/routes_to_swagger_docs/schema/generator/path_generator.rb, lib/routes_to_swagger_docs/schema/generator/schema_generator.rb
- Implement `RoutesToSwaggerDocs::Schema::Base#save_path_for` 
- Remove unnecessary methods
=> Unified save path methods

lib/routes_to_swagger_docs/schema/analyzer/components/schemas_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/path_analyzer.rb
- SchemaSchema => Filter
- PathSchema   => Filter
=> Rename private classes

README.md, docs/HOW_TO_USE_SCHEMA_NAMESPACE.md, docs/HOW_TO_USE_TAG_NAMESPACE.md, lib/routes_to_swagger_docs/configuration.rb, lib/routes_to_swagger_docs/routing/adjustor.rb, lib/routes_to_swagger_docs/routing/base.rb, lib/routes_to_swagger_docs/routing/parser.rb, lib/routes_to_swagger_docs/schema/generator.rb, lib/routes_to_swagger_docs/schema/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/generator/components/schema_generator.rb, lib/routes_to_swagger_docs/schema/generator/components_generator.rb, lib/routes_to_swagger_docs/schema/generator/schema_generator.rb, lib/routes_to_swagger_docs/schema/v3/openapi_object.rb, lib/routes_to_swagger_docs/schema/v3/path_item_object.rb, lib/routes_to_swagger_docs/schema/v3/paths_object.rb, lib/routes_to_swagger_docs/shared/searchable.rb
- Support `use_tag_namespace` option.
- Support `use_schema_namespace` option.
- Support  multiple `components_schema_paths` ( `$ref` )
=> Support use namespace options

README.md, docs/HOW_TO_ANALYZE_DOCS.md, lib/routes_to_swagger_docs/schema/analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/base_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/components/schemas_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/components_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/path_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/tag_analyzer.rb, lib/routes_to_swagger_docs/schema/base.rb, lib/routes_to_swagger_docs/schema/editor.rb, lib/routes_to_swagger_docs/schema/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/generator/doc_generator.rb, lib/routes_to_swagger_docs/tasks/swagger.rake
- Implement `routes:swagger:analyze` rake tasks
- Import from existing schema
=> Analyze from exists schemas

lib/routes_to_swagger_docs/routing/adjustor.rb, lib/routes_to_swagger_docs/schema/v3/path_item_object.rb
- Use brach( `{}` ) instead of symbl( `:` ) for parameter style.
- Delegate parameters in path for Adjustor class.
=> Use brace({}) instead of symbol(:) for parameter style

lib/routes_to_swagger_docs/schema/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/generator/components/request_body_generator.rb, lib/routes_to_swagger_docs/schema/generator/components/schema_generator.rb, lib/routes_to_swagger_docs/schema/generator/components_generator.rb, lib/routes_to_swagger_docs/schema/squeezer/components/request_body_squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/components_squeezer.rb
- Implement `Components::RequestBodyGenerator`
- Implement `Components::RequestBodySqueezer`
- Implement `(private)BaseGenerator#deep_search_components_file_recursive`
- Modify `(private)BaseGenerator#components_schemas_file_paths`
- Rename from `components_schemas_file_paths` to `components_file_paths`
=> Support components request bodies ref

README.md, lib/routes_to_swagger_docs/configuration.rb, lib/routes_to_swagger_docs/schema/editor.rb
Save edited tmp schema in interval
=> Save edited tmp schema in interval

lib/routes_to_swagger_docs/schema/v3/paths_object.rb
Fatal Bug !!!!
Fix RoutesToSwaggerDocs::Schema::V3::PathsObject#to_doc.
=> Fix RoutesToSwaggerDocs::Schema::V3::PathsObject#to_doc

lib/routes_to_swagger_docs/schema/analyzer/base_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/components/request_bodies_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/components/schemas_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/path_analyzer.rb, lib/routes_to_swagger_docs/schema/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/generator/components/request_body_generator.rb, lib/routes_to_swagger_docs/schema/generator/components/schema_generator.rb, lib/routes_to_swagger_docs/schema/generator/doc_generator.rb, lib/routes_to_swagger_docs/schema/generator/path_generator.rb, lib/routes_to_swagger_docs/shared/all.rb, lib/routes_to_swagger_docs/shared/sortable.rb
Force sort  src of swagger_docs when generate and analyze
=> Force sort by target (path / schemas / requestBodies )

lib/routes_to_swagger_docs/routing/adjustor.rb, lib/routes_to_swagger_docs/routing/components/all.rb, lib/routes_to_swagger_docs/routing/components/base_component.rb, lib/routes_to_swagger_docs/routing/components/path_component.rb, lib/routes_to_swagger_docs/routing/components/request_component.rb, lib/routes_to_swagger_docs/routing/components/verb_component.rb
Implement
- PathComponent
- RequestComponent
- VerbComponent
=> Refactor adjustor by create routing components

lib/routes_to_swagger_docs/configuration.rb, lib/routes_to_swagger_docs/logger/stdout_logger.rb, lib/routes_to_swagger_docs/schema/base.rb, lib/routes_to_swagger_docs/schema/editor.rb, lib/routes_to_swagger_docs/task_logging.rb
=> Implement/Use StdoutLogger  (fix #28)

README.md, lib/routes_to_swagger_docs/configuration.rb, lib/routes_to_swagger_docs/configuration/paths_config.rb, lib/routes_to_swagger_docs/schema/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/generator/doc_generator.rb, lib/routes_to_swagger_docs/schema/generator/path_generator.rb, lib/routes_to_swagger_docs/schema/squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/base_squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/components/request_body_squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/components/schema_squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/components_squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/path_squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/tag_squeezer.rb, lib/routes_to_swagger_docs/tasks/common.rake
Writing file paths in .paths will only read them.
`swagger_docs/.paths`
```
schema/paths/account_user_role.yml
schema/paths/account.yml
```
=> Writing file paths in .paths will only read them

README.md, docs/HOW_TO_MONITOR_SWAGGER_DOC.md, lib/routes_to_swagger_docs/schema/analyzer/base_analyzer.rb, lib/routes_to_swagger_docs/schema/monitor.rb, lib/routes_to_swagger_docs/tasks/swagger.rake
Implement rake task.
`bundle exec rake routes:swagger:monitor`
=> Implement monitor rake task

lib/routes_to_swagger_docs/schema/analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/tag_analyzer.rb, lib/routes_to_swagger_docs/schema/editor.rb, lib/routes_to_swagger_docs/schema/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/manager/diff/base_hash_diff_manager.rb, lib/routes_to_swagger_docs/schema/manager/diff/components/request_body_diff_manager.rb, lib/routes_to_swagger_docs/schema/manager/diff/components/schema_diff_manager.rb, lib/routes_to_swagger_docs/schema/manager/pathname_manager.rb, lib/routes_to_swagger_docs/tasks/tool.rake
- Fix `routes:swagger:analyze` rake task
- Modify `routes:swagger:paths_ls` rake task
- Fix `PathnameManager` class
- Save edited schema data in file when editing
=> Fix bugs for rake tasks

README.md, docs/HOW_TO_CLEAN_DOCS.md, lib/routes_to_swagger_docs/base.rb, lib/routes_to_swagger_docs/schema/cleaner.rb, lib/routes_to_swagger_docs/schema/cleaner/base_cleaner.rb, lib/routes_to_swagger_docs/schema/cleaner/components_cleaner.rb, lib/routes_to_swagger_docs/schema/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/generator/components/request_body_generator.rb, lib/routes_to_swagger_docs/schema/generator/components/schema_generator.rb, lib/routes_to_swagger_docs/tasks/main.rake
- Implement `routes:swagger:clean`
- Modify README and Add emoji ☺️
=> Implement cleaner rake task

lib/routes_to_swagger_docs/schema/generator/base_generator.rb
Fix bugs when bundle exec rake routes:swagger:docs initialy
=> Fix bugs when generate docs initialy

lib/routes_to_swagger_docs/schema/analyzer/components/request_bodies_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/components/schemas_analyzer.rb, lib/routes_to_swagger_docs/schema/manager/diff/base_hash_diff_manager.rb
If you delete components/schemas/properties all, File is deleted automaticaly.
=> Fixed a problem that occurred when editing  `components/schemas`

.gitignore, README.md, docs/versions/v3.md, lib/routes_to_swagger_docs/schema/analyzer/components/security_schemes_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/components_analyzer.rb, lib/routes_to_swagger_docs/schema/analyzer/path_analyzer.rb, lib/routes_to_swagger_docs/schema/cleaner/components_cleaner.rb, lib/routes_to_swagger_docs/schema/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/generator/components/security_sheme_generator.rb, lib/routes_to_swagger_docs/schema/manager/diff/components/security_scheme_diff_manager.rb, lib/routes_to_swagger_docs/schema/manager/file/components/request_body_file_manager.rb, lib/routes_to_swagger_docs/schema/manager/file/components/security_scheme_file_manager.rb, lib/routes_to_swagger_docs/schema/manager/file/components_file_manager.rb, lib/routes_to_swagger_docs/schema/manager/file/include_ref_base_file_manager.rb, lib/routes_to_swagger_docs/schema/manager/file/path_item_file_manager.rb, lib/routes_to_swagger_docs/schema/manager/pathname_manager.rb, lib/routes_to_swagger_docs/schema/squeezer/base_squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/components/security_scheme_squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/components_squeezer.rb, lib/routes_to_swagger_docs/schema/squeezer/path_squeezer.rb
to analyze k8s api document
https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json
- Fixed circular reference bug
- Automatically set `unknown` when tag is not set
- Automatically generated when TagObject is not defined(when analyze)
- Support `components/securitySchemes`
- Support all path item object fixed fields when analyze
- $ref
- summary
- description
- get
- put
- post
- delete
- options
- head
- patch
- trace
- servers
- parameters
=> to analyze k8s api document successful

docs/versions/v3.md, lib/routes_to_swagger_docs/base.rb, lib/routes_to_swagger_docs/schema/v3/analyzer/base_analyzer.rb, lib/routes_to_swagger_docs/schema/v3/base.rb, lib/routes_to_swagger_docs/schema/v3/cleaner/base_cleaner.rb, lib/routes_to_swagger_docs/schema/v3/generator/base_generator.rb, lib/routes_to_swagger_docs/schema/v3/manager/diff/base_diff_manager.rb, lib/routes_to_swagger_docs/schema/v3/manager/file/base_file_manager.rb, lib/routes_to_swagger_docs/schema/v3/manager/pathname_manager.rb
- Support components objects
- responses
- examples
- headers
- links
- callbacks
=> Support all components objects

README.md, lib/routes_to_swagger_docs/tasks/main.rake
Implement `bundle exec rake routes:swagger:dist`
=> Implement routes:swagger:dist rake task

README.ja.md, lib/r2-oas/schema/generator.rb
=> Remove pry dep

CHANGELOG.md, Gemfile.lock, README.ja.md, README.md, r2-oas.gemspec, spec/spec_helper.rb
- Add `CHANGELOG.md`
- Update `README.md`
- Configure coveralls
=> Add CHANGELOG

README.ja.md, README.md
=> Cosme README

README.ja.md, README.md, docs/README.md
=> Add usage video

README.ja.md, README.md, docs/README.md, docs/usage/analyze_docs.md, docs/usage/deploy_docs.md, docs/usage/display_paths_list.md, docs/usage/edit_docs.md, docs/usage/generate_docs.md, docs/usage/monitor_docs.md, docs/usage/use_hook_to_generate_docs.md, docs/usage/view_docs.md, lib/r2-oas/schema/v3/analyzer/components/object_analyzer.rb, lib/r2-oas/schema/v3/analyzer/path_analyzer.rb, lib/r2-oas/schema/v3/analyzer/tag_analyzer.rb, lib/r2-oas/schema/v3/cleaner/base_cleaner.rb, lib/r2-oas/schema/v3/generator/components/object_generator.rb, lib/r2-oas/schema/v3/generator/components/request_body_generator.rb, lib/r2-oas/schema/v3/generator/doc_generator.rb, lib/r2-oas/schema/v3/generator/path_generator.rb, lib/r2-oas/schema/v3/generator/schema_generator.rb, lib/r2-oas/schema/v3/manager/file/base_file_manager.rb, lib/r2-oas/tool/paths/ls.rb, r2-oas.gemspec
Fix #110
Change log display to relative path
<details>
```
$ bundle exec rake routes:oas:docs
I, [2020-04-27T19:38:50.325882 #21628]  INFO -- : [R2-OAS] start
I, [2020-04-27T19:38:50.757996 #21628]  INFO -- : [Generate OAS schema files] start
I, [2020-04-27T19:38:50.758299 #21628]  INFO -- : <From routes data>
I, [2020-04-27T19:38:50.758318 #21628]  INFO -- : <Update schema files>
I, [2020-04-27T19:38:50.759848 #21628]  INFO -- :  Write schema file: 	oas_docs/src/openapi.yml
I, [2020-04-27T19:38:50.760922 #21628]  INFO -- :  Write schema file: 	oas_docs/src/info.yml
I, [2020-04-27T19:38:50.762564 #21628]  INFO -- :  Write schema file: 	oas_docs/src/tags.yml
I, [2020-04-27T19:38:50.762582 #21628]  INFO -- :  [Generate OAS schema files (paths)] start
I, [2020-04-27T19:38:50.763383 #21628] …
```
=> Change log display to relative path

CHANGELOG.md, Gemfile.lock, lib/r2-oas/version.rb
Deploy v0.1.3
```
$ bundle exec rake build
r2-oas 0.1.3 built to pkg/r2-oas-0.1.3.gem.
```
=> Deploy v0.1.3

CHANGELOG.md, GEMSPEC.md, Gemfile.lock, README.ja.md, README.md, docs/README.md, lib/r2-oas/version.rb, r2-oas.gemspec
- Update Usage gif
- Upgrade gemspec
- bump minor
=> Before release v0.2.0

docs/_sidebar.md, docs/attention/if_clash.md, docs/trableshouting/runtime_error.md
=> Add docs about Trableshouting [skip ci]

CHANGELOG.md, lib/r2-oas/version.rb
- Update ChangeLog
- Bump minor
=> Before release 0.3.0

CHANGELOG.md, lib/r2-oas/version.rb
- Update CHANGELOG
- bump patch
=> Before release v0.3.1

CHANGELOG.md, lib/r2-oas/version.rb
- Update CHANGELOG
- bump patch
=> Before release v0.3.2

CHANGELOG.md, lib/r2-oas/version.rb
- Update CHANGELOG.md
- bump patch
=> Before release v0.3.3

CHANGELOG.md, lib/r2-oas/version.rb, r2-oas.gemspec
- Add `r2-oas.gemspec` into gemspec `files`
=> Before release v0.3.4

CHANGELOG.md, lib/r2-oas/version.rb
- bump minor
- Update CHANGELOG
=> Before release v0.4.0

CHANGELOG.md, lib/r2-oas/version.rb
- Update CHANGELOG
- bump patch
=> before release v0.4.1

CHANGELOG.md, lib/r2-oas/version.rb
=> Before release v0.5.0

README.md
Corrections while reading the README.md for the first time
Thanks for writing this tool. I just made some readme corrections as I was reading through it for the first time.
Really very tame changes, thanks again!
=> Just some quick typo fixes
